apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bert-mlops-pipeline
  namespace: argo-cd-nebius-demo-gk
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/geetakudumula/nebius-bert-demo-gitops
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: soperator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
